name: Flutter Web Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build web

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: password-generator-web
        path: ./build/web/
        retention-days: 5