name: Flutter Web Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter pub get
    # - run: flutter test
    - name: Get repository name
      id: version
      run: |
        REPOSITORY=$(echo ${{ github.repository }} | sed -e "s#.*/##")
        echo ::set-output name=repository::$REPOSITORY
    - run: flutter build web --web-renderer html --base-href /${{ steps.version.outputs.repository }}/
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
